### PR TITLE
find and children async

### PR DESCRIPTION
**Pull request by aboire**
## What

Add the possibility that "find" and "children" are async

## Why

With Meteor async migration, there may be cases where awaiting for results is needed inside the callback.

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]
LGTM

**Comment by StorytellerCZ** [comment]
Published in v1.8.2

**Comment by StorytellerCZ** [comment]
@aboire can you please look into #167? It seem to have started happening after this. So far I have not been able to identify where exactly things get broken, so if we don't resolve this quickly I will have to reverse this PR early next week.

**Comment by aboire** [comment]
@StorytellerCZ Do you know how to reproduce the error? I asked for more information on the issue

**Comment by aboire** [comment]
@StorytellerCZ if you understand correctly, it is that it is no longer parallel which creates the problem because at the time of unpublish the children the entry this.documents[docId] is deleted before going through all the chidrens so I think when replacing in _publishChildrenOf "for of" by "Promise.all" that should solve the problem

**Comment by nachocodoner** [comment]
I believe some tests could have been added as part of this feature. Great to see this implemented though!

**Pull request merged**
