### PR TITLE
Fix Issue #68

### PR DESCRIPTION
**Pull request by Data-Meister**
Fixes critical bug which causes problems when you have 3 or more levels of publication. 

See issue #68

### CODE REVIEW

**Comment by Data-Meister** [comment]
Intuitively and from what I understand of the flow the first commit should work. 

However it does not because sometimes the parent publication that's calling _republishChildrenOf sometimes has the same number of args as the child publication. 

This suggests that _republishChildrenOf is being called by a sibling publication not the parent. 

I don't understand the flow perfectly so not sure if this is a feature or a bug (perhaps a reference modification related bug). 

I added a hack to the fix and it now seems to work perfectly. 

Happy to engage in further discussion with someone who knows the library better about making a neater fix.

Since this is now a semi-official part of Meteor referenced by the Official Guide it would be good to make it very stable and I'm more than happy to assist with that :)

**Comment by reywood** [comment]
Hmm, this seems to be fixing a symptom rather than the actual problem. I appreciate the help, but it seems we need to figure out why a child publication is getting the wrong arguments.

**Comment by Data-Meister** [comment]
Yes the second commit is just fixing a symptom. I couldn't figure out why it was happening. I'll make a simple sample application where the symptom occurs. 

Re: the first commit... previously only the first argument was being updated (with the new doc). There was no attempt to pass down other arguments which could have been updated by ancestor publication changes cascading down. Is there some other reason for the previous behavior?

**Comment by Data-Meister** [comment]
Here's a test repo: 

https://github.com/Data-Meister/test_publish_composite_update_array_bug

I forked from darkship's repo referenced in #68:

https://github.com/darkship/test_publish_composite_update_array_bug

Darkship's repo shows the problem the first commit solves. 

My repo shows when the second commit (the hack) gets activated. In this case the hack is triggered on the first and second times you click the button. 

In this simple example it runs OK without the hack. But in my client's app it causes an error. 

If you like I can make a more complex test repo showing where the error happens. But if you are able to shed some light on why the hack is triggered in this simple case that might be all we need to solve this. 

I think (but _not_ sure) it might have something to do with combining publish and republish.

**Comment by StorytellerCZ** [comment]
@Data-Meister Can you please update this?

**Comment by Data-Meister** [comment]
@StorytellerCZ I stopped using this library. I'd recommend [this one instead](https://github.com/peerlibrary/meteor-reactive-publish).

It's very powerful. Can do everything this one can, and more. Has excellent unit test coverage with some interesting examples.

**Comment by StorytellerCZ** [comment]
@Data-Meister As much as I like Mitar, I just don't want to have Coffee Script. I'll take this as a no then.

**Comment by Data-Meister** [comment]
@StorytellerCZ you app doesn't need to use Coffee Script, it can be ES6. Doesn't matter what the library is written in, does it? CS is just JS, and CS might not even be a dep (it needn't be). 

Mitar's libraries are indeed impressive, and are mostly written in CS. Personally I like using them, but up to you.

I had some big problems with this library so I don't want to spend time to re-familiarize myself and maintain it. You should be able to make a copy of my commit and submit your own PR if you want to though.

**Pull request closed without merging**
